Add zenodo doi
hyperspy/rosettasciio pull request #149
Opened 2023-07-19 15:12 UTC by jlaehne

### Description of the change
Add citing section with zenodo doi and credits section to main page of user guide.

### Progress of the PR
- [X] Change implemented (can be split into several points),
- [X] update user guide (if appropriate),
- [ ] add a changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/rosettasciio/blob/main/upcoming_changes/README.rst)),
- [ ] Check formatting of the changelog entry (and eventual user guide changes) in the `docs/readthedocs.org:rosettasciio` build of this PR (link in github checks)
- [ ] ready for review.

2023-07-24 14:20 UTC, pietsjoh requested changes

2023-07-24 14:20 UTC, pietsjoh commented on docs/index.rst
> +RosettaSciIO is maintened by `an active community of developers
maintained

2023-08-02 16:39 UTC, ericpre approved these changes

2023-08-02 16:39 UTC, ericpre commented on docs/index.rst
> +RosettaSciIO is maintened by `an active community of developers
```suggestion
RosettaSciIO is developed by `an active community of developers
```

2023-08-07 10:23 UTC, jlaehne commented
Thanks @pietsjoh for catching this copy-pasted typo from HyperSpy, I submitted a PR to fix it there as well: https://github.com/hyperspy/hyperspy/pull/3211

@ericpre - indeed RSciIO is more in a development state ... but "developed by ... developers" is not the nicest phrasing either? So I am considering to stick with "maintained".

2023-08-07 17:18 UTC, ericpre commented
Would "RosettaSciIO is developed by an active community of contributors" be better?

2023-08-07 19:59 UTC, merged